apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend
  namespace: campusvault

spec:
  replicas: 1

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
      - name: backend
        image: 877270729772.dkr.ecr.ap-south-1.amazonaws.com/campusvault-backend:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        ports:
        - containerPort: 8080

        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://postgres-service:5432/campusvault

        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: campusvault-secret
              key: DB_USERNAME

        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: campusvault-secret
              key: DB_PASSWORD

        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          value: update