apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: campusvault-ingress
  namespace: campusvault

spec:
  ingressClassName: nginx

  rules:
  - host: campusvault.local

    http:
      paths:

      - path: /
        pathType: Prefix

        backend:
          service:
            name: frontend-service
            port:
              number: 80

      - path: /api
        pathType: Prefix

        backend:
          service:
            name: backend-service
            port:
              number: 8080